<?php
// French translation - v2.1
// Labels used for different portions of the plugin
$labels = array();
$labels['autoreply'] = 'Rép. autom.';
$labels['plugin_explanation'] = 'Sur cette page, vous pouvez configurer une réponse automatique.';
$labels['maindiv_title'] = 'Réponse automatique (Autoresponder)';
$labels['enabled'] = 'Activée';
$labels['from'] = 'Du (p.ex. %s)';
$labels['to'] = 'Au (p.ex. %s)';
$labels['subject'] = 'Sujet';
$labels['msg'] = 'Message';
$labels['user_dateformat'] = 'd.m.Y';

// Messages used for the different portions of the plugin
$messages = array();
$messages['internal_error'] = 'Autoresponder: Une erreur interne est survenue.';
$messages['update_error'] = 'Autoresponder: La mise à jour de la réponse automatique a échouée.';
$messages['insert_error'] = 'Autoresponder: La configuration de réponse automatique a échouée.';
$messages['invalid_to_date'] = 'Autoresponder: Vous avez spécifié une date de fin qui est dans le passé.';
$messages['invalid_interval'] = 'Autoresponder: Vous avet spécifié un interval invalide. La date de fin doit dépasser la date de début.';
$messages['db_conn_err'] = 'Autoresponder: La connexion à la base de données à échouée.';
$messages['successfully_saved'] = 'Vous avez engregistré(e) la réponse automatique avec succès pour';
$messages['missing_subject'] = 'Veuillez s.v.p. préciser un sujet de la réponse automatique.';
$messages['missing_message'] = 'Veuillez s.v.p. préciser un message de la réponse automatique.';
?>
