<?php
// Luxembourgish translation - v2.1
// Labels used for different portions of the plugin
$labels = array();
$labels['autoreply'] = 'Autom. Äntwert';
$labels['plugin_explanation'] = 'Hei kennt Dir eng automatesch Äntwert op E-Mailen ariichten.';
$labels['maindiv_title'] = 'Automatesch Äntwert (Autoresponder)';
$labels['enabled'] = 'Aktivéiert';
$labels['from'] = 'Vun (zB. %s)';
$labels['to'] = 'Bis (zB. %s)';
$labels['subject'] = 'Sujet';
$labels['msg'] = 'Message';
$labels['user_dateformat'] = 'd.m.Y';

// Messages used for the different portions of the plugin
$messages = array();
$messages['internal_error'] = 'Autoresponder: En interne Fehler ass opgetrueden.';
$messages['update_error'] = 'Autoresponder D\'Beaarbechtung vun der Astellung huet net funktionéiert.';
$messages['insert_error'] = 'Autoresponder: D\'Afügen an d\'Datebank huet net funktionéiert.';
$messages['invalid_to_date'] = 'Autoresponder: Et gouf ee "bis"-Datum uginn, deen an der Vergaangenheet läit.';
$messages['invalid_interval'] = 'Autoresponder: Et gouf en ongültegt Intervall uginn. D\'"bis"-Datum muss virum "vum"-Datum leien.';
$messages['db_conn_err'] = 'Autoresponder: Et gouf e Fehler bei der Datebankverbindung.';
$messages['successfully_saved'] = 'Dir hutt d\'Automatesch Äntwert erfollegräich ageriicht fir';
$messages['missing_subject'] = 'Gidd w.e.g. e Sujet un.';
$messages['missing_message'] = 'Gidd w.e.g. e Message un.';
?>
